name: Stream to Facebook Live (Stable and High Quality)

on:
  push:
    branches:
      - main
  workflow_dispatch: # لبدء البث يدويًا من GitHub

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up FFmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Start stable stream
        env:
          STREAM_KEY: ${{ secrets.FACEBOOK_STREAM_KEY }}
        run: |
          ffmpeg -re -i "https://live4.beinconnect.us/YallaGoalApp/beINSports1.m3u8" \
          -c:v libx264 -preset veryfast -crf 23 -maxrate 3000k -bufsize 6000k \
          -g 50 -c:a aac -b:a 128k -ar 44100 -f flv \
          "rtmps://live-api-s.facebook.com:443/rtmp/${STREAM_KEY}"
